Document: glues
Title: Debian glues Manual
Author: <insert document author here>
Abstract: This manual describes what glues is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glues/glues.sgml.gz

Format: postscript
Files: /usr/share/doc/glues/glues.ps.gz

Format: text
Files: /usr/share/doc/glues/glues.text.gz

Format: HTML
Index: /usr/share/doc/glues/html/index.html
Files: /usr/share/doc/glues/html/*.html
